'use strict';

/* voa.js — VOA Non-Domestic Rating lookup
   Loads data/voa/{AREA}.json on demand (generated by scripts/process_voa.py
   then split by scripts/split_voa.py).
   Provides postcode-based lookups for factory/warehouse/workshop entries.
   England and Wales only. */

const VOA = (() => {

  const _cache   = {};   /* area → postcode → [{c, l, rv, a}] */
  const _loading = {};   /* area → in-flight fetch promise */
  const _failed  = new Set();

  /* Rateable value → rough size/value band label */
  function _rvBand(rv) {
    if (!rv) return null;
    if (rv >= 500000) return 'Major industrial site';
    if (rv >= 100000) return 'Large industrial property';
    if (rv >=  50000) return 'Medium industrial property';
    if (rv >=  15000) return 'Small–medium unit';
    if (rv >=   5000) return 'Small unit';
    return 'Micro unit';
  }

  function _normalise(pc) {
    const parts = pc.trim().toUpperCase().split(/\s+/);
    if (parts.length === 2) return `${parts[0]} ${parts[1]}`;
    const r = pc.trim().toUpperCase().replace(/\s/g, '');
    return r.length >= 5 ? `${r.slice(0, -3)} ${r.slice(-3)}` : r;
  }

  function _area(normalisedPc) {
    const m = normalisedPc.match(/^([A-Z]+)/);
    return m ? m[1] : null;
  }

  async function _loadArea(area) {
    if (_cache[area])   return _cache[area];
    if (_failed.has(area)) return null;
    if (_loading[area]) return _loading[area];

    _loading[area] = fetch(`data/voa/${area}.json`)
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then(d => {
        _cache[area]   = d;
        delete _loading[area];
        return d;
      })
      .catch(err => {
        console.warn(`[VOA] Could not load voa/${area}.json:`, err.message);
        _failed.add(area);
        delete _loading[area];
        return null;
      });

    return _loading[area];
  }

  /* Look up all industrial entries at a postcode.
     Returns array of {code, label, rateableValue, rvBand, address} or [] */
  async function lookup(postcode) {
    if (!postcode) return [];
    const pc   = _normalise(postcode);
    const area = _area(pc);
    if (!area) return [];

    const d = await _loadArea(area);
    if (!d) return [];

    return (d[pc] || []).map(e => ({
      code:          e.c,
      label:         e.l,
      rateableValue: e.rv,
      rvBand:        _rvBand(e.rv),
      address:       e.a,
    }));
  }

  /* True if the given area has been loaded */
  function isAvailable() { return Object.keys(_cache).length > 0; }

  /* No-op preload — loading is on-demand now */
  function preload() {}

  return { lookup, isAvailable, preload };
})();
