'use strict';

/* voa.js — VOA Non-Domestic Rating lookup
   Loads data/voa_industrial.json (generated by scripts/process_voa.py)
   and provides postcode-based lookups for factory/warehouse/workshop entries.
   England and Wales only. */

const VOA = (() => {

  let _data     = null;   /* postcode → [{c, l, rv, a}] */
  let _loading  = null;   /* in-flight fetch promise */
  let _failed   = false;

  /* Rateable value → rough size/value band label */
  function _rvBand(rv) {
    if (!rv) return null;
    if (rv >= 500000) return 'Major industrial site';
    if (rv >= 100000) return 'Large industrial property';
    if (rv >=  50000) return 'Medium industrial property';
    if (rv >=  15000) return 'Small–medium unit';
    if (rv >=   5000) return 'Small unit';
    return 'Micro unit';
  }

  function _normalise(pc) {
    const parts = pc.trim().toUpperCase().split(/\s+/);
    if (parts.length === 2) return `${parts[0]} ${parts[1]}`;
    const r = pc.trim().toUpperCase().replace(/\s/g, '');
    return r.length >= 5 ? `${r.slice(0, -3)} ${r.slice(-3)}` : r;
  }

  async function _load() {
    if (_data)   return _data;
    if (_failed) return null;
    if (_loading) return _loading;

    _loading = fetch('data/voa_industrial.json')
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then(d => {
        _data    = d;
        _loading = null;
        return d;
      })
      .catch(err => {
        console.warn('[VOA] Could not load voa_industrial.json:', err.message);
        _failed  = true;
        _loading = null;
        return null;
      });

    return _loading;
  }

  /* Look up all industrial entries at a postcode.
     Returns array of {code, label, rateableValue, rvBand, address} or [] */
  async function lookup(postcode) {
    if (!postcode) return [];
    const d = await _load();
    if (!d) return [];

    const pc      = _normalise(postcode);
    const entries = d[pc] || [];

    return entries.map(e => ({
      code:          e.c,
      label:         e.l,
      rateableValue: e.rv,
      rvBand:        _rvBand(e.rv),
      address:       e.a,
    }));
  }

  /* True if the data file has been loaded successfully */
  function isAvailable() { return _data !== null; }

  /* Preload in the background — call once on app start */
  function preload() { _load(); }

  return { lookup, isAvailable, preload };
})();
