'use strict';

/* voa_geo.js — VOA spatial gap-finder layer
   Loads data/voa_geo.json (generated by scripts/geocode_voa.py).
   Each entry: postcode → [lat, lng, count, maxRV, topCode]

   findGaps(bounds, osmElements) returns two buckets:
     gaps    — VOA postcodes with no OSM industrial feature within THRESHOLD metres
     matched — VOA postcodes that have a nearby OSM feature (confirming coverage)
*/

const VOAGeo = (() => {

  const THRESHOLD = 60;   /* metres — OSM feature must be within this to count as matched */

  let _data    = null;
  let _loading = null;
  let _failed  = false;

  const CODE_LABELS = {
    IF: 'Factory', IF3: 'Workshop', IF4: 'Industrial Unit',
    IW: 'Warehouse', IW3: 'Storage Premises', IB: 'Business Units',
    IH: 'Workshop', IL: 'Light Industrial', IS: 'Storage',
  };

  async function _load() {
    if (_data)    return _data;
    if (_failed)  return null;
    if (_loading) return _loading;

    _loading = fetch('data/voa_geo.json')
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then(d => {
        _data    = d;
        _loading = null;
        return d;
      })
      .catch(err => {
        console.warn('[VOAGeo] Could not load voa_geo.json:', err.message);
        _failed  = true;
        _loading = null;
        return null;
      });

    return _loading;
  }

  /* Haversine distance in metres */
  function _distM(lat1, lng1, lat2, lng2) {
    const R  = 6371000;
    const φ1 = lat1 * Math.PI / 180;
    const φ2 = lat2 * Math.PI / 180;
    const Δφ = (lat2 - lat1) * Math.PI / 180;
    const Δλ = (lng2 - lng1) * Math.PI / 180;
    const a  = Math.sin(Δφ/2) ** 2 + Math.cos(φ1) * Math.cos(φ2) * Math.sin(Δλ/2) ** 2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  }

  /* Extract centroids from loaded OSM elements */
  function _osmCentroids(elements) {
    const pts = [];
    for (const el of elements) {
      if (el.type === 'node') {
        pts.push({ lat: el.lat, lng: el.lon });
      } else if (el.geometry && el.geometry.length) {
        let lat = 0, lng = 0;
        for (const p of el.geometry) { lat += p.lat; lng += p.lon; }
        pts.push({ lat: lat / el.geometry.length, lng: lng / el.geometry.length });
      }
    }
    return pts;
  }

  /* RV band label */
  function _rvBand(rv) {
    if (!rv)          return 'Unrated';
    if (rv >= 500000) return 'Major site';
    if (rv >= 100000) return 'Large';
    if (rv >=  50000) return 'Medium';
    if (rv >=  15000) return 'Small–medium';
    if (rv >=   5000) return 'Small';
    return 'Micro';
  }

  /* Returns { gaps, matched, total } for the given Leaflet bounds.
     If osmElements is empty/null, every VOA postcode in bounds is a gap. */
  async function findGaps(bounds, osmElements) {
    const d = await _load();
    if (!d) return { gaps: [], matched: [], total: 0 };

    const s = bounds.getSouth(), n = bounds.getNorth();
    const w = bounds.getWest(),  e = bounds.getEast();

    const osmPts = osmElements ? _osmCentroids(osmElements) : [];

    const gaps    = [];
    const matched = [];

    for (const [pc, v] of Object.entries(d)) {
      const [lat, lng, count, maxRV, topCode] = v;
      if (lat < s || lat > n || lng < w || lng > e) continue;

      const item = {
        pc, lat, lng, count, maxRV,
        topCode,
        label:  CODE_LABELS[topCode] || topCode,
        rvBand: _rvBand(maxRV),
      };

      const hasNearby = osmPts.some(p => _distM(lat, lng, p.lat, p.lng) < THRESHOLD);
      (hasNearby ? matched : gaps).push(item);
    }

    return { gaps, matched, total: gaps.length + matched.length };
  }

  function isAvailable() { return _data !== null; }
  function preload()     { _load(); }

  return { findGaps, isAvailable, preload, CODE_LABELS };
})();
